application: one-hour-investor
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /.*
  script: onehourinvestor.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
